/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_Dien;

import javax.swing.JOptionPane;

public class GiaoDienMenuChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienMenuChinh
     */
    public GiaoDienMenuChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTieuDe = new javax.swing.JLabel();
        jPanelMenuChinh = new javax.swing.JPanel();
        jButtonQLSP = new javax.swing.JButton();
        jButtonQLNCC = new javax.swing.JButton();
        jButtonQLPX = new javax.swing.JButton();
        jButtonQLNV = new javax.swing.JButton();
        jButtonQLTK = new javax.swing.JButton();
        jButtonQLDT = new javax.swing.JButton();
        jButtonQLPN = new javax.swing.JButton();
        jButtonQLCTPX = new javax.swing.JButton();
        jThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý đồ ăn nhanh căng tin số 2 - ĐH Công nghiệp Hà Nội");
        setAlwaysOnTop(true);

        jLabelTieuDe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTieuDe.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTieuDe.setText("QUẢN LÝ ĐỒ ĂN NHANH CĂNG TIN  SỐ 2 - ĐH CÔNG NGHIỆP HÀ NỘI");

        jButtonQLSP.setLabel("Quản Lý Sản Phẩm");
        jButtonQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLSPActionPerformed(evt);
            }
        });

        jButtonQLNCC.setText("Quản Lý Nhà Cung Cấp");
        jButtonQLNCC.setToolTipText("");
        jButtonQLNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLNCCActionPerformed(evt);
            }
        });

        jButtonQLPX.setText("Quản Lý Phiếu Xuất");
        jButtonQLPX.setToolTipText("");
        jButtonQLPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLPXActionPerformed(evt);
            }
        });

        jButtonQLNV.setText("Quản Lý Nhân Viên");
        jButtonQLNV.setToolTipText("");
        jButtonQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLNVActionPerformed(evt);
            }
        });

        jButtonQLTK.setText("Quản Lý Tài Khoản");
        jButtonQLTK.setToolTipText("");
        jButtonQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLTKActionPerformed(evt);
            }
        });

        jButtonQLDT.setText("Quản Lý Doanh Thu");
        jButtonQLDT.setToolTipText("");
        jButtonQLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLDTActionPerformed(evt);
            }
        });

        jButtonQLPN.setText("Quản Lý Phiếu Nhập");
        jButtonQLPN.setToolTipText("");
        jButtonQLPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLPNActionPerformed(evt);
            }
        });

        jButtonQLCTPX.setText("Quản Lý Chi Tiết Phiếu Xuất");
        jButtonQLCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLCTPXActionPerformed(evt);
            }
        });

        jThoat.setText("Thoát");
        jThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuChinhLayout = new javax.swing.GroupLayout(jPanelMenuChinh);
        jPanelMenuChinh.setLayout(jPanelMenuChinhLayout);
        jPanelMenuChinhLayout.setHorizontalGroup(
            jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuChinhLayout.createSequentialGroup()
                        .addComponent(jThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMenuChinhLayout.createSequentialGroup()
                        .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMenuChinhLayout.createSequentialGroup()
                                .addComponent(jButtonQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(jButtonQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMenuChinhLayout.createSequentialGroup()
                                .addComponent(jButtonQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonQLNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMenuChinhLayout.createSequentialGroup()
                                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonQLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonQLPX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonQLCTPX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        jPanelMenuChinhLayout.setVerticalGroup(
            jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuChinhLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQLNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQLPX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelMenuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQLCTPX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonQLSP.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanelMenuChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMenuChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLSPActionPerformed
        // TODO add your handling code here:
        GiaoDienQLSanPham x = new GiaoDienQLSanPham();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLSPActionPerformed

    private void jButtonQLNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLNCCActionPerformed
        // TODO add your handling code here:
        GiaoDienQLNCC x = new GiaoDienQLNCC();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLNCCActionPerformed

    private void jButtonQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLNVActionPerformed
        // TODO add your handling code here:
        GiaoDienQLNhanVien x =  new GiaoDienQLNhanVien();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLNVActionPerformed

    private void jButtonQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLTKActionPerformed
        // TODO add your handling code here:
        GiaoDienQLTaiKhoan x = new GiaoDienQLTaiKhoan();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLTKActionPerformed

    private void jButtonQLPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLPXActionPerformed
        // TODO add your handling code here:
       GiaoDienQLPhieuXuat x =  new GiaoDienQLPhieuXuat();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLPXActionPerformed

    private void jButtonQLPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLPNActionPerformed
        // TODO add your handling code here:
        GiaoDienQLPhieuNhap x = new GiaoDienQLPhieuNhap();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLPNActionPerformed

    private void jButtonQLCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLCTPXActionPerformed
        // TODO add your handling code here:
        GiaoDienQLCTPhieuXuat x = new GiaoDienQLCTPhieuXuat();
          x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLCTPXActionPerformed

    private void jButtonQLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLDTActionPerformed
        // TODO add your handling code here:
        GiaoDienDoanhThu x = new GiaoDienDoanhThu();
            x.setVisible(true);
        x.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonQLDTActionPerformed

    private void jThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThoatActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienMenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienMenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienMenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienMenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new  GiaoDienMenuChinh().setVisible(true);
//               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQLCTPX;
    private javax.swing.JButton jButtonQLDT;
    private javax.swing.JButton jButtonQLNCC;
    private javax.swing.JButton jButtonQLNV;
    private javax.swing.JButton jButtonQLPN;
    private javax.swing.JButton jButtonQLPX;
    private javax.swing.JButton jButtonQLSP;
    private javax.swing.JButton jButtonQLTK;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JPanel jPanelMenuChinh;
    private javax.swing.JButton jThoat;
    // End of variables declaration//GEN-END:variables
}
